[package]
name = "glang"
repository = "https://github.com/mpsoftwarefoundation/GeorgeLanguage.git"
description = "The George Programming Language"
version = "0.0.0"
edition = "2024"

[dependencies]
simply_colored = "0.1.0"
