[package]
name = "glang"
repository = "https://github.com/mpsoftwarefoundation/GeorgeLanguage.git"
description = "The George Programming Language"
authors = ["MP Software Foundation"]
version = "0.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
simply_colored = "0.1.0"

[features]
default = []
benchmark = []
