[package]
name = "glang-attributes"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
simply_colored = "0.1.0"

[features]
features = []
