name: GLang MacOS Build

on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin,aarch64-apple-darwin

      - name: Build for x86_64
        run: cargo build --release --target x86_64-apple-darwin

      - name: Build for aarch64
        run: cargo build --release --target aarch64-apple-darwin

      - name: Combine into universal binary
        run: |
          mkdir -p dist/GeorgeLanguage
          lipo -create \
            target/x86_64-apple-darwin/release/glang \
            target/aarch64-apple-darwin/release/glang \
            -output dist/GeorgeLanguage/glang
          chmod +x dist/GeorgeLanguage/glang

      - name: Copy repo folders
        run: |
          cp -r library dist/GeorgeLanguage/
          cp -r LICENSE dist/GeorgeLanguage/
          cp -r README.md dist/GeorgeLanguage/

      - name: Create zip file
        run: |
          cd dist
          zip -r GeorgeLanguage+macos_setup.zip GeorgeLanguage

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: GeorgeLanguage+macos_setup
          path: dist/GeorgeLanguage+macos_setup.zip

      - name: Upload zip
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: dist/GeorgeLanguage+macos_setup.zip
